config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get "/signup" =>"users#signup",:as => "signup"
  get "/login" =>"users#login",:as => "login"
  get "/redirect" =>"welcome#redirect",:as => "redirect"
  post 'create_login_session' => 'users#create_login_session'
 
  delete "logout" => "users#logout", :as => "logout"

  get "/houses" =>"houses#index",:as => "houses"
  get "/houses/letters" =>"houses#letters"
  post "/houses/letters" =>"houses#letters"

  get "/admin" =>"welcome#admin",:as => "admin"
  get "/userbooks" =>"userbooks#index",:as =>"userbooks"
  get "/userbooks/publish" =>"userbooks#publish"
  get "publish" =>"articles#publish",:as => "publish"
  get "/allinfos" =>"allinfos#index",:as =>"allinfos"
  get "/allinfos/newinfo" =>"allinfos#newinfo",:as =>"newinfo"
  get "/allinfos/join/:allinfo_id/:user_id" =>"allinfos#join"
  get "/shares" =>"shares#index",:as => "shares"
  get "/shares/newshare" =>"shares#newshare",:as => "newshares"
  get "/monthly" =>"monthly#index",:as => "monthly"
  get "/drifts" =>"drifts#index",:as => "drifts"
  get "/swaps" =>"swaps#index",:as => "swaps"
  get "/swaps/newswap" =>"swaps#newswap",:as => "newswaps"
  get "/swaps/join/:swap_id/:user_id" =>"swaps#join"

  resources :users, only:[:create]
  resources :goodsinfos
  resources :userbooks
  resources :articles
  resources :allinfos
  resources :shares  
  resources :swaps
  resources :letters

    root 'welcome#index'

end

app/models/allinfo.rb
class Allinfo < ActiveRecord::Base
  belongs_to :user
  has_many :oneinfo
  validates :title, :price, :max, :url, :user_id, :presence => true
end

app/models/article.rb
class Article < ActiveRecord::Base

  belongs_to :user

  validates :title, :body, :user_id, :presence => true
end

app/models/goodsinfo.rb
class Goodsinfo < ActiveRecord::Base
end

app/models/home.rb
class Home < ActiveRecord::Base
end

app/models/house.rb
class House < ActiveRecord::Base
end

app/models/houses.rb
class Houses < ActiveRecord::Base
end

app/models/letter.rb
class Letter < ActiveRecord::Base
  belongs_to :user
end

app/models/oneinfo.rb
class Oneinfo < ActiveRecord::Base
  belongs_to :allinfo
  validates :joined_id, :presence => true
end

app/models/share.rb
class Share < ActiveRecord::Base
  belongs_to :user
end

app/models/swap.rb
class Swap < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles
  has_many :userbooks
  has_many :allinfos
  has_many :shares
  has_many :swaps
  has_many :letters
  
	has_secure_password
  #attr_accessible :email, :name, :password, :password_confirmation, :tokenend
	before_create { generate_token(:token) }

	validates :name, :presence => true, :uniqueness => {:case_sensitive => false}
  validates :email, :presence => true, :uniqueness => {:case_sensitive => false}, :email_format => true
  validates :password, :length => { :minimum => 6 }, :on => :create

	def user_params 
	  params.require(:user).permit(:username, :email)
	end 

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end
end

app/models/userbook.rb
class Userbook < ActiveRecord::Base
  belongs_to :user
  validates :title, :body, :desc, :user_id, :presence => true
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def admin
  	@users = User.all
  	@goodsinfos = Goodsinfo.all

  end 
  
  def index
    if !current_user
      redirect_to :login,:notice =>"请先登录或注册。"
    else
      @goodsinfos = Goodsinfo.all
      @shares = Share.all
      @user = User.find(current_user)
      @letters = Letter.all
      @letter = @user.letters.build(params[:letter])
    end

  end
  	
  def redirect
		redirect_to :root ,:notice =>"注册成功"
  end
  private
    def letter_params
      params.require(:letter).permit(:title, :from_id, :belong_id, :content)
    end
end

app/helpers/allinfos_helper.rb
module AllinfosHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/drifts_helper.rb
module DriftsHelper
end

app/helpers/letters_helper.rb
module LettersHelper
end

app/helpers/monthly_helper.rb
module MonthlyHelper
end

app/helpers/shares_helper.rb
module SharesHelper
end

app/helpers/swaps_helper.rb
module SwapsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_info.html.erb
  <table class="text-center">
    <% @goodsinfos.each do |goodsinfo| %>
      <tr class="highlight">
        <td><%= goodsinfo.title %></td>
        <td><%= goodsinfo.url %></td>
          <td><%= link_to 'Show', goodsinfo_path(goodsinfo),class:"btn btn-info" %></td>
          <td><%= link_to 'Edit', edit_goodsinfo_path(goodsinfo),class:"btn btn-primary" %></td>
          <td><%= link_to 'Destroy', goodsinfo_path(goodsinfo),class:"btn btn-danger",
              method: :delete, data: { confirm: 'Are you sure?' } 
              %>
      </tr>
    <% end %>
  </table>

app/views/welcome/_manage.html.erb
<table class="table">
  <thead>
    <tr>
      <th>用户名</th>
      <th>邮箱</th>
    </tr>
  </thead>
  <tbody>
	<% @users.each do |t| %> 
	  <tr>
	  <td><%= t.name %></td>
	  <td><%= t.email %></td>
	  </tr>
	<% end %>  
  </tbody>
</table>

app/views/welcome/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Dashboard">
    <meta name="keyword" content="Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">

    <title>后台</title>

    <!-- Bootstrap core CSS -->
    <%= stylesheet_link_tag "css/admin/style" %>
    <%= stylesheet_link_tag "css/admin/style-responsive" %>
    
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

  <section id="container" >
      <header class="header black-bg">
              <div class="sidebar-toggle-box">
                  <div class="fa fa-bars tooltips" data-placement="right" data-original-title="Toggle Navigation"></div>
              </div>
            <!--logo start-->
            <a href="index.html" class="logo"><b>圣院后台</b></a>
            <!--logo end-->

            <div class="top-menu">
            	<ul class="nav pull-right top-menu">
                    <li><a class="logout" href="login.html">Logout</a></li>
            	</ul>
            </div>
        </header>
      <aside>
          <div id="sidebar"  class="nav-collapse sidemenu">
              <!-- sidebar menu start-->
              <ul class="sidebar-menu" id="nav-accordion">
              	  <h5 class="centered">圣院后台管理</h5>
              	  	
                  <li class="info">

                      <a href="">
                          <i class="fa fa-dashboard"></i>
                          <span>优惠信息推送</span>
                      </a>
                  </li>

                  <li class="manage">
                      <a href="">
                          <i class="fa fa-desktop"></i>
                          <span>成员管理</span>
                      </a>
                  </li>

                  <li class="sort">
                      <a href="" >
                          <i class="fa fa-cogs"></i>
                          <span>经史子集</span>
                       <!--史部，收录史书。子部，收录诸子百家著作和类书。集部，收录诗文词总集和专集等。-->
                      </a>
                  </li>
                  <li class="library">
                      <a href="">
                          <i class="fa fa-book"></i>
                          <span>藏书阁</span>
                      </a>
                  </li>
                  <li class="admin">
                      <a href="">
                          <i class="fa fa-tasks"></i>
                          <span>管理员设置</span>
                      </a>
                  </li>

              </ul>
              <!-- sidebar menu end-->
          </div>
      </aside>
      <!--main content start-->
      <section id="main-content">
          <section class="wrapper">
      			<div class="show_info hide">
      			  <%= render partial: 'info' %>
      			</div>
            <div class="show_manage hide">
              <%= render partial: 'manage' %>
            </div>
            <div class="show_sort hide">
              <%= render partial: 'sort' %>
            </div>
              <div class="show_library hide">
              <%= render partial: 'library' %>
            </div>
               <div class="show_admin hide">
              <%= render partial: 'admin' %>
            </div>
          </section>
      </section>

  </section>

  </body>
    <%= javascript_include_tag "admin/jquery.js" %>
    <%= javascript_include_tag "admin/bootstrap.js" %>
    <%= javascript_include_tag "admin/dcjqaccordion.js" %>
    <%= javascript_include_tag "admin/scrollTo.js" %>
    <%= javascript_include_tag "admin/common-scripts.js" %>
<script>
$('document').ready(function(){
  $('.wrapper').children('.info').show();
  $('.sidemenu ul li').click(function(e){
    var thisClass = $(this).attr('class');
    $('.wrapper').children().addClass('hide');
    $('.wrapper').children('.' + "show_" + thisClass).removeClass('hide');
    e.preventDefault();
  });
});
  

</script>

app/views/welcome/index.html.erb
<title>千千静阅</title>    
<style>
  body{
    background-image: url('<%= asset_path("nice_snow.png") %>');
  }
</style>
<body>
 
    <!-- menu navigation -->
    <header class="header">
      <div class="navigation spy">
          <ul class="nav">
              <li class="hide">
                  <a href="#top"></a>
              </li>
              <% if current_user %>
                <li><%= link_to current_user.name,houses_path %></li>
                <li class="notifications dropdown">
                    <a href="javascript:;" data-toggle="dropdown">
                        <i class="ti-bell"></i>
                        <div class="badge badge-top bg-danger animated flash">

                          <% @letter_find = @letters.where(belong_id: @user.id) %>
                          <% @letter_num1 = @letter_find.count %>
                          <% @letter_num2 = @letter_find.where(state:-1).count%>
                            <span><%= @letter_num1 - @letter_num2  %></span>
                        </div>
                    </a>
                </li>
                <li><%= link_to "退出", logout_path, method: "delete" %></li>
              <% else %>
                <li>
                  <%= link_to "Login", "login", class: "nav-btn btn btn-btn-rounded" %>
                </li>
                <li>
                  <%= link_to "Sign Up", "signup", class: "nav-btn btn btn-success btn-rounded" %>
                </li>
              <% end %>
          </ul>
      </div>
    </header>
    <!-- /menu navigation -->
    <section class="content-section banner">
        <div class="parallax-cover parallax-0" style="background-image: url(img/cover3.jpg);"></div>

        <div class="overlay-darken-4"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <div class="text-center">
                        <blockquote class="text-white">
                            <p>Education is not to implant, but the lighting of flames（教育的意义是点燃希望的火苗，而不是装满一个容器。）</p>
                            <small class="color">Socrates （苏格拉底）</small>
                        </blockquote>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- statistics -->
    <section id="statistics" class="content-section banner parallax color-inherit text-white text-center" style="background-image: url(img/cover2.jpg);">

        <div class="overlay-colored-3"></div>

        <div class="container">
            <div class="row">
                <div class="col-sm-3 col-xs-6 p15">
                    <i class="fa fa-home icon-size"></i>
                    <b class="count" data-from="0" data-to="6850" data-appear-top-offset="-200">0</b>
                    <span>
                    <% if current_user %>
                        <%= link_to "黄金屋", "houses", class: "heading-font heading-size btn btn-white btn-lg btn-outline" %>
                        <% else %>
                        <%= link_to "黄金屋", "redirect", class: "heading-font heading-size btn btn-white btn-lg btn-outline" %>
                    <% end %>
                   </span>
                </div>
                
                <div class="col-sm-3 col-xs-6 p15">
                    <i class="fa fa-book icon-size"></i>
                    <b class="count" data-from="0" data-to="1000" data-appear-top-offset="-200">0</b>
                    <%= link_to "笔记月刊", "monthly", class: "heading-font heading-size btn btn-white btn-lg btn-outline" %>
                </div>

                <div class="col-sm-3 col-xs-6 p15">
                    <i class="fa fa-road icon-size"></i>
                    <b class="count" data-from="0" data-to="2300" data-appear-top-offset="-200">0</b>
                    <%= link_to "图书漂流", "drifts", class: "heading-font heading-size btn btn-white btn-lg btn-outline" %>
                </div>

                <div class="col-sm-3 col-xs-6 p15">
                    <i class="count-icon ti-na"></i>
                    <b class="count" data-from="0" data-to="8650" data-appear-top-offset="-200">0</b>
                   <%= link_to "以旧易书", "swaps", class: "heading-font heading-size btn btn-white btn-lg btn-outline" %>
                </div>

            </div>
        </div>

    </section>
    <!-- /statistics -->
    <section class="services container clearfix mt25 mb25"> 
            <!-- Services List  -->
            <div class="services_list col-xs-12">
                    <div class="col-xs-4 table-responsive">
                               <table class="table table-hover">
                                   <thead>
                                     <tr>
                                       <th class="text-center">
                                         <h4>图书优惠/折扣</h4>
                                       </th>
                                     </tr>
                                   </thead>
                                   <tbody>
                                      <% @goodsinfos.each do |goodsinfo| %>
                                         <tr>
                                           <td class="text-center">
                                      <%= link_to goodsinfo.title, goodsinfo.url, class: "nav-btn btn btn-btn-rounded",target:"_blank" %>
                                           </td>
                                         </tr>
                                       <% end %>
                                   </tbody>
                                </table>
                    </div>
                    <div class="col-xs-4 table-responsive">
                         <table class="table table-hover">
                           <thead>
                             <tr>
                               <th class="text-center"><h4>热门书单</h4></th>
                             </tr>
                           </thead>
                           <tbody>
                             <tr>
                               <td class="text-center"><a href="http://www.jianshu.com/p/df3e68422c1d">2014年书单</a></td>
                             </tr>
                             <tr>
                               <td class="text-center"><a href="http://www.jianshu.com/p/f4df107d6946">2015年书单</a></td>
                             </tr>
                           </tbody>
                         </table>
                    </div>
                    <div class="col-xs-4 table-responsive">
                         <table class="table table-hover">
                           <thead>
                             <tr>
                               <th class="text-center"><h4>最新资源</h4></th>
                             </tr>
                           </thead>
                           <tbody>
                              <% @shares.each do |share| %>
                                 <tr>
                                   <td class="text-center">
                              <%= link_to share.title,"/shares", class: "nav-btn btn btn-btn-rounded",target:"_blank" %>
                                   </td>
                                 </tr>
                               <% end %>
                           </tbody>
                         </table>
                    </div>
            </div>
    </section>
    <div>
    <section class="mt25 mb25">
      <div class="container">
        <div class="col-xs-12">
          <div class="col-xs-3">
            <div class="feature-icon bordered text-center">
                <i  class="ti-pencil-alt color"></i>
            </div>
            <div class="feature-description text-center">
                <h5>
                    <span class="btn"><%= link_to "笔记广场", articles_path ,target:"_blank" %></span>
                    <small class="show text-muted">读书笔记，妙笔文章。</small>
                </h5>
                <p>好记性不如烂笔头，分享心得，分享阅读的快乐。</p>
            </div>
          </div>
          <div class="col-xs-3">
            <div class="feature-icon bordered text-center">
                <i class="ti-bookmark-alt color"></i>
            </div>
            <div class="feature-description text-center">
                <h5>
                    <span class="btn"><%= link_to "以书会友", userbooks_path ,target:"_blank" %></span></span>
                    <small class="show text-muted">畅所欲言，以书会友</small>
                </h5>
                <p>抛砖引玉，以书聚友。</p>
            </div>
          </div>
          <div class="col-xs-3">
            <div class="feature-icon bordered text-center">
                <i class="fa fa-shopping-cart color"></i>
            </div>
            <div class="feature-description text-center">
                <h5>
                    <span class="btn"><%= link_to "凑单团", allinfos_path ,target:"_blank" %></span></span>
                    <small class="show text-muted">加入凑单团，以最实惠的价格购书。</small>
                </h5>
                <p>多人凑单买书，呼朋唤友。</p>
            </div>
          </div>
          <div class="col-xs-3">
            <div class="feature-icon bordered text-center">
                <i class="fa fa-gift color"></i>
            </div>
            <div class="feature-description text-center">
                <h5>
                    <span class="btn"><%= link_to "资源共享", shares_path ,target:"_blank"%></span></span>
                    <small class="show text-muted">分享拥有的电子书以及其它资源。</small>
                </h5>
                <p>当你急需一些稀缺书籍，不妨来这发布需求。</p>
            </div>
          </div>
        </div>
      </div>
    </section>
    <footer class="content-section backimg">
        <div class="container">
            <div class="row text-center">
                <div class="col-sm-12 mb25">
                    <a class="btn btn-primary btn-social-icon btn-rounded btn-outline btn-sm smooth-scroll mb25" href="#top">
                        <i class="ti-angle-up"></i>
                    </a>
                    <br>
                </div>
                <div class="col-sm-12 mb25">
                    <p class="text-center">
                        Copyright &copy;
                        <span id="year" class="mr5"></span>
                        <span>临水照影</span>
                    </p>
                </div>
            </div>
        </div>
    </footer>
    <!-- /footer -->

    <%= javascript_include_tag "jqueryx" %>
    <%= javascript_include_tag "lightSlider" %>
    <script>
      $(document).ready(function() {
        $("#scorll").lightSlider({
            loop:true,
            keyPress:true
        });
      });
     </script>
</body>